spring.config.import=file:.env[.properties]
spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.security.enabled=false

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.web.cors.allowed-origin-patterns=${CORS_ALLOWED_ORIGINS}
spring.web.cors.exposed-headers=${CORS_EXPOSED_HEADERS}
spring.web.cors.max-age=${CORS_MAX_AGE}
spring.web.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
spring.web.cors.allowed-methods=${CORS_ALLOWED_METHODS}
spring.web.cors.allowed-headers=${CORS_ALLOWED_HEADERS}
spring.web.cors.allow-credentials=${CORS_ALLOW_CREDENTIALS}